// Top-level build file where you can add configuration options common to all sub-projects/modules.
plugins {
    alias(libs.plugins.kotlin.android) apply false
    alias(libs.plugins.kotlin.compose) apply false
    alias(libs.plugins.android.library) apply false
    alias(libs.plugins.android.application) apply false
    //alias(libs.plugins.google.devtools.ksp) apply false
}

ext {
    tarSdkVer = 34
    compSdkVer = 34
    minSdkVer = 23

    debugAlias = "photo.gallery"
    releaseAlias = "photo.gallery"
    debugStore = "droidaiokeystore"
    releaseStore = "droidaiokeystore"
    debugPassword = "droidaiokeystore"
    releasePassword = "droidaiokeystore"
    keyStoreFile = file(System.getProperty("user.home") + "/.android/keys/DroidAIO_KeysStore.jks")
    appname = "\"Photo Gallery\""
    company = "\"DroidAIO Devs\""
    author2 = "\"AI Assistant (developed by Google)\""
    author1 = "\"C Marx Chako <cmarxchako@gmail.com>\""
    developer = "\"AnDroid All In One Software Developers (DroidAIO Devs)\""
}


